export const GET_REQUEST = 'GET_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_EMAIL = 'GET_EMAIL';

export const GET_EMAIL_PARTNER = 'GET_EMAIL_PARTNER';

export const GET_AUTH_USAHA = 'GET_AUTH_USAHA';

export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILURE = 'GET_USER_DETAIL_FAILURE';

export const GET_CATEGORY_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_GENRES_FAILURE';

export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE';

export const GET_MITRA_DETAIL_SUCCESS = 'GET_MITRA_DETAIL_SUCCESS';
export const GET_MITRA_DETAIL_FAILURE = 'GET_MITRA_DETAIL_FAILURE';

// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNX0sImlhdCI6MTYyMjM2MDkzNywiZXhwIjoxNjI3NTQ0OTM3fQ._njp4KBl2aa10cpmTvXN6pMJoDwObGjWwHWcUZS8QlQ
// https://techstop.gabatch11.my.id

// token partner
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0bmVyIjp7ImlkIjozNn0sImlhdCI6MTYyMjQxMDU4OSwiZXhwIjoxNjI3NTk0NTg5fQ.ttZSKrHXqonv1Uf7KMtiKNB8HTUVOAwYTDSyua5tJe8
